from django.test import TestCase
from projects.forms import ProjectCreateForm
from accounts.models import User
from projects.models import Project

# Create your tests here.
class BasicFormValidationTests(TestCase):
  
  # Simple user and root project to initialize the form
  def setUp(self):
    self.user = User.objects.create_user(username='testuser', password='password')
    # root is automatically generated by the signal after the user creation
    self.root = Project.objects.get(owner=self.user, parent=None) 

  # BASIC test:
  def test_project_form_fails_with_empty_title(self):
    # Form data with empty title
    form_data = {
      'title': '', 
      'visibility': 'priv', 
      'description': 'A test project'
    }
    form = ProjectCreateForm(data=form_data, user=self.user, parent_project=self.root)
    self.assertFalse(form.is_valid()) # Form has to be non valid
    self.assertIn('title', form.errors) # title field needs to be in the error dict