# Generated by Django 6.0.5 on 2026-06-19 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('owner',), name='unique_root_project_per_user', violation_error_message='A user has one and only one root project.'),
        ),
    ]
