# Generated by Django 6.0.5 on 2026-06-19 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_unique_root_project_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='projectpermission',
            name='unique_user_project_permission',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_permission', violation_error_message='A user can have at most only one permission on the same project.'),
        ),
    ]
