# Generated by Django 6.0.5 on 2026-06-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectpermission_unique_user_project_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
