# Generated by Django 6.0.5 on 2026-06-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='project_parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='projects.project'),
        ),
    ]
