# Generated by Django 6.0.5 on 2026-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todolist_creation_date_remove_todolist_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoentry',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
