# Generated by Django 6.0.5 on 2026-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todoentry_completion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoentry',
            options={'ordering': ['is_completed', models.OrderBy(models.F('deadline'), nulls_last=True)]},
        ),
        migrations.AddConstraint(
            model_name='todoentry',
            constraint=models.UniqueConstraint(fields=('todo', 'content'), name='unique_todo_content', violation_error_message='A task with this name already exists in this list.'),
        ),
    ]
